"""add custom fields for users

Revision ID: 4e5aae670b34
Revises: d8f6795b1448
Create Date: 2025-09-10 15:06:44.414269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e5aae670b34"
down_revision: Union[str, Sequence[str], None] = "d8f6795b1448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    player_role_enum = postgresql.ENUM(
        "CARRY",
        "MIDLANER",
        "OFFLANER",
        "SOFT_SUPPORT",
        "HARD_SUPPORT",
        name="player_role",
    )
    player_role_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.add_column(
        "users", sa.Column("display_name", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("steam_id", sa.String(length=20), nullable=True))
    op.add_column(
        "users", sa.Column("steam_profile_url", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "main_role",
            postgresql.ENUM(
                "CARRY",
                "MIDLANER",
                "OFFLANER",
                "SOFT_SUPPORT",
                "HARD_SUPPORT",
                name="player_role",
            ),
            nullable=True,
        ),
    )
    op.add_column("users", sa.Column("current_mmr", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("peak_mmr", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("country", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("social_links", sa.JSON(), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=200), nullable=True)
    )
    op.add_column("users", sa.Column("last_stats_update", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_users_steam_id"), "users", ["steam_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_steam_id"), table_name="users")
    op.drop_column("users", "last_stats_update")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "social_links")
    op.drop_column("users", "country")
    op.drop_column("users", "bio")
    op.drop_column("users", "peak_mmr")
    op.drop_column("users", "current_mmr")
    op.drop_column("users", "main_role")
    op.drop_column("users", "steam_profile_url")
    op.drop_column("users", "steam_id")
    op.drop_column("users", "display_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
